const Outreach = () => {
  return (
    <div className="max-w-7xl mx-auto p-6 space-y-6">
      <div className="flex items-center justify-between mb-4">
        <h1 className="text-2xl font-semibold">Candidate Outreach</h1>
      </div>
      <p>Facilisis dictumst dui venenatis a tincidunt nisi ullamcorper pretium class parturient parturient vestibulum habitasse parturient cras ullamcorper conubia etiam a elementum fames sem ac gravida a cum adipiscing quisque a. Consectetur in donec vestibulum gravida integer a est pharetra leo parturient purus fames a ut scelerisque a a dui felis elementum dui erat. Mi parturient penatibus urna vestibulum a at suspendisse cubilia a scelerisque interdum sociis enim ut vestibulum id nisi vestibulum suscipit suspendisse lobortis integer blandit a aliquam scelerisque consequat parturient. Velit diam vivamus cras adipiscing nisl a sit cum lacus a ullamcorper lacus justo parturient suspendisse in eget vehicula. A ut aliquet orci vestibulum ullamcorper adipiscing adipiscing praesent vestibulum nostra cum quis a et a dictum magna lobortis at. Habitant vestibulum egestas lacinia posuere quis a porta platea pretium est cursus ultricies curabitur sociosqu laoreet est egestas auctor a nisl morbi ac vestibulum erat a fames. Netus vehicula dolor imperdiet fermentum eu non condimentum hac vestibulum suspendisse potenti gravida ad aptent nulla cubilia metus consequat sagittis fringilla magnis vestibulum lacus euismod.

A ac tincidunt sit rhoncus consectetur sem vestibulum quam velit diam a ultrices sem mattis commodo vestibulum a amet adipiscing eleifend dolor. Pretium tortor elit phasellus per taciti a laoreet consequat suspendisse nascetur donec parturient cum lobortis ultrices. Porttitor malesuada ut vestibulum a at vel parturient scelerisque molestie parturient sed suspendisse pretium adipiscing integer hac adipiscing a magna proin. Risus viverra consectetur ullamcorper at a a senectus suspendisse scelerisque parturient auctor a aliquam in ullamcorper vestibulum. Massa consectetur cursus cursus litora accumsan augue dictumst ac donec suscipit varius feugiat a arcu suspendisse a parturient nec rhoncus id adipiscing vestibulum.

Ac phasellus nostra scelerisque non aenean sagittis adipiscing placerat a eget feugiat dui suspendisse vel ullamcorper ac parturient maecenas a vestibulum natoque semper senectus habitant condimentum euismod elit. Integer scelerisque lobortis condimentum nulla sociis integer eget velit velit molestie elit parturient ac ullamcorper hendrerit a dapibus curabitur ligula a sed parturient eu sem. Condimentum odio conubia bibendum in rhoncus leo dis suspendisse scelerisque nisl habitant ac eu ultrices ullamcorper id vestibulum eu condimentum parturient potenti. Fusce magna vulputate fringilla iaculis quis aenean tempor venenatis convallis eros ante eleifend scelerisque leo per scelerisque diam dignissim risus primis eu curae in inceptos molestie dictumst iaculis massa. Parturient vestibulum egestas scelerisque turpis ac vel est et facilisis magnis consectetur vestibulum adipiscing cubilia habitant ullamcorper a sapien malesuada vestibulum primis condimentum rutrum a ut nam. Potenti scelerisque suspendisse a ullamcorper donec dictumst a ornare adipiscing adipiscing praesent vestibulum vestibulum ultrices tincidunt a.

Rhoncus integer condimentum vestibulum enim rhoncus parturient litora scelerisque vestibulum suspendisse ornare at sem mattis at congue. Consequat enim at tempus ac donec adipiscing velit a nibh per cum a nullam penatibus parturient. Venenatis maecenas ullamcorper dui himenaeos accumsan a montes eu sed faucibus ad pharetra nec diam rhoncus. Quisque nullam malesuada parturient nec nibh ad maecenas a placerat vestibulum cubilia consequat dis per. A ad elementum a a tellus scelerisque mus turpis rutrum scelerisque in turpis adipiscing integer a in lorem imperdiet neque parturient placerat a. A consectetur vestibulum arcu a ac egestas cubilia metus fermentum fermentum duis ad quam mi.

Maecenas a primis ut urna sem id semper sociis phasellus imperdiet congue eu convallis erat condimentum a a. Suspendisse sem eu elit phasellus per tempus viverra nec bibendum purus porttitor vestibulum consectetur vestibulum porta justo erat a sem dolor per. Mauris a leo convallis a adipiscing volutpat bibendum commodo consectetur fermentum ullamcorper a commodo vivamus nam iaculis id eu parturient erat venenatis justo. Ornare scelerisque a mauris morbi ullamcorper malesuada a mi id adipiscing arcu id vehicula nisl nisi nulla dictum ultrices gravida donec.

Sed consectetur morbi a dis cubilia ante dignissim malesuada et fringilla sodales praesent bibendum penatibus vestibulum mus. Eu suscipit vestibulum a magna curabitur a a sapien a parturient pulvinar tempus primis class per torquent varius vestibulum ipsum est aliquet nisi. Aenean adipiscing sociosqu commodo vivamus dui aptent dolor cras aliquam condimentum vulputate augue augue phasellus purus suscipit ut parturient fames. Platea a vitae pretium habitant vel eleifend adipiscing vestibulum augue nibh sodales dui nascetur nulla sociosqu sagittis orci sem.

Fusce ut lacus quis consectetur per est cursus a sed in ullamcorper consequat facilisis gravida integer ullamcorper cum hac inceptos a sociosqu a a adipiscing praesent varius vestibulum aliquam. Enim vestibulum ut amet nunc adipiscing suspendisse nec lacinia ut ac tortor platea velit blandit adipiscing ad justo at consectetur placerat consequat fusce dui a. Ad montes euismod phasellus diam id a sit ullamcorper donec proin a eros elit sodales ante adipiscing a malesuada suscipit et urna arcu quam vel id sed nec a. Eu scelerisque volutpat parturient in et posuere vestibulum euismod per elementum vestibulum malesuada ac id vestibulum varius ut ac. Pretium consectetur porttitor suspendisse a placerat adipiscing lobortis vestibulum pharetra maecenas condimentum interdum at a ut bibendum eleifend venenatis nam class inceptos nascetur hac dignissim ultricies.

Hac mi mi suspendisse taciti nec suspendisse erat adipiscing a duis porta condimentum suspendisse scelerisque a torquent a. Metus nec vestibulum parturient tellus nullam condimentum adipiscing fermentum penatibus a tempor pretium rutrum elit dapibus at. A consectetur litora himenaeos nisl convallis fringilla a diam sed ligula diam parturient a fames consectetur arcu vel parturient a faucibus. Integer ac nibh cras adipiscing justo scelerisque torquent sem vestibulum cras a tincidunt scelerisque condimentum quam.

Cras leo scelerisque diam vestibulum nascetur est faucibus placerat scelerisque cubilia at a sapien consectetur.Viverra mi ullamcorper vestibulum fermentum sodales etiam lobortis libero a suspendisse nascetur tellus sem hac nisl vel vestibulum a magna molestie felis mattis a.Sapien in vehicula mus himenaeos fusce.</p>
    </div>
  );
};

export default Outreach;
